### ISSUE TITLE
Edpuzzle

### ISSUE THREAD

**Issue by Etantheprawn** [ading2210/edpuzzle-answers#61] opened 2024-05-21 18:45 UTC
It seems as the the new tab does open but it is stuck on fetching assignments… it has been on it for a few minutes and the speed and pause on unfocus doesn’t work neither. It was working just fine yesterday but today, it’s broken. 

Best regards, Unknown

**Comment by ading2210** [comment] 2024-06-04 00:31
Duplicate of #57

**Closed by ading2210** 2024-06-04 00:31 UTC
Labels: duplicate
