### ISSUE TITLE
it wont show the answers and the options dont work, the answers completly vanished???..

### ISSUE THREAD

**Issue by 44011406** [ading2210/edpuzzle-answers#33] opened 2024-01-09 18:13 UTC
[
![Screenshot 2024-01-09 1 11 57 PM](https://github.com/ading2210/edpuzzle-answers/assets/123180419/9613156f-d6bf-486c-b1f4-24f1d6afc22d)
](url)
![Screenshot 2024-01-09 1 11 57 PM](https://github.com/ading2210/edpuzzle-answers/assets/123180419/991dc3d8-0616-4c52-b95d-8128992bc1a4)

**Comment by ading2210** [comment] 2024-01-09 20:14
Duplicate of #27.

**Closed by ading2210** 2024-01-09 20:14 UTC

**Comment by TopchetoEU** [comment] 2024-10-25 16:12
@ading2210
sorry to necropost, but why was the infamous #27 removed? did the skid request it? i'm trying to document the whole happening because it was just so hilarious history can't afford to forget it

**Comment by ading2210** [comment] 2024-10-25 23:42
@TopchetoEU Their account was banned because they started spamming slurs on the issues in this repo.
