### ISSUE TITLE
Fetching assignments..

### ISSUE THREAD

**Issue by Lolbozo30207** [ading2210/edpuzzle-answers#34] opened 2024-01-22 14:41 UTC
When I click on a edpuzzzle it says fetching assignments but for other ones it doesnt do that
![Screenshot 2024-01-22 9 41 34 AM](https://github.com/ading2210/edpuzzle-answers/assets/93811991/c60420a3-87b5-4482-ae6e-72e5170b6cf0)

**Comment by ading2210** [comment] 2024-01-23 04:57
This is a duplicate of #27.

**Closed by ading2210** 2024-01-23 04:57 UTC
Labels: duplicate
